### ISSUE TITLE
[dev-app] Incorrect checksum on dev app for 1_beta9

### ISSUE THREAD

**Issue by chongyic** [solettaproject/meta-soletta#81] opened 2016-05-25 10:01 UTC
The checksum for dev-app tarball on commit [8a256b9bd1bf9fbec56255115519594e314bbbdb](https://github.com/solettaproject/meta-soletta/commit/8a256b9bd1bf9fbec56255115519594e314bbbdb) does not match with the checksum of  the file posted on release page.
Please refer to error messgae below:

``````
ERROR: soletta-dev-app-1_beta9-r0 do_fetch: Fetcher failure for URL: 'https://github.com/solettaproject/soletta-dev-app/releases/download/v1_beta9/soletta-dev-app_standalone_v1_beta9.tar.gz;protocol=archive'. Checksum mismatch!
File: '/home/ilab/yocto/poky/build/downloads/soletta-dev-app_standalone_v1_beta9.tar.gz' has md5 checksum d6a08e58d14d4dd46fd7d5c27811132f when 33f2eba375ec72f8eb7a39d32e3acb1a was expected
File: '/home/ilab/yocto/poky/build/downloads/soletta-dev-app_standalone_v1_beta9.tar.gz' has sha256 checksum 13f9829758e500d6de9215cc459be4f3953153a486dc8ce8c0aba8e3ee161e64 when f225d43265a474a97c22c237c30237fb3a4e01a272538a32379b2fc4e62413f0 was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "d6a08e58d14d4dd46fd7d5c27811132f"
SRC_URI[sha256sum] = "13f9829758e500d6de9215cc459be4f3953153a486dc8ce8c0aba8e3ee161e64"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly `modified.```


``````

**Comment by brunobottazzini** [comment] 2016-05-25 19:19
@chongyic, fix proposed in PR: https://github.com/solettaproject/meta-soletta/pull/84

Could you check if the issue is resolved ?

**Comment by chongyic** [comment] 2016-05-27 00:33
@brunobottazzini @lblim

Checksum seems correct now.
Thanks.

**Comment by brunobottazzini** [comment] 2016-05-30 14:52
@chongyic thanks patch merged

**Closed as completed by brunobottazzini** 2016-05-30 14:52 UTC
